json.extract! business, :id,
                        :name,
                        :address,
                        :city,
                        :state,
                        :zipcode,
                        :phone,
                        :url,
                        :lat,
                        :lng,
                        :owner_id,
                        :price
